baseURL                     = "https://jklmf.github.io/"
languageCode                = "en-us"
defaultContentLanguage      = "en"
isMultilingual              = false
title                       = "Falcon from hardware"
theme                       = "sam"
pygmentsStyle               = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences          = true
# googleAnalytics           = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "lmf.falcon@gmail.com"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"
    # rss                = ""

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "about"
    text = "Falcon in hardware"

[[params.mainMenu]]
    link = "https://www.linkedin.com/in/falcon-lmf-44050665/"
    text = "linkedin"

[[params.mainMenu]]
    link = "https://github.com/falconlmf/"
    text = "</> github"

[imaging]
    quality = 75